from langgraph.graph import MessagesState
from langgraph.prebuilt.chat_agent_executor import AgentState
from typing import List, Optional

class nomad_visa_state(AgentState):
    main_goal: str
    nationality: Optional[str]
    additional_passport: Optional[str]
    additional_residency: Optional[str]
    current_work_situation: Optional[str]
    current_job_industry: Optional[str]
    company_registered_at_home: Optional[str]
    will_open_company_at_abroad: Optional[str]
    monthly_income: Optional[str]
    personal_savings: Optional[str]
    destination_country: Optional[str]
    duration_of_stay: Optional[str]
    tax_benefits_option: Optional[str]
    help_open_bank_account: Optional[str]
    extend_stay_option: Optional[str]
    solo_or_family: Optional[str]
    number_of_dependents: Optional[str]
    accomodation_help: Optional[str]
    flight_booking_help: Optional[str]
    visa_denied_previously: Optional[str]
    criminal_record: Optional[str]
    

class investment_visa_state(AgentState):
    main_goal: str
    nationality: Optional[str]
    additional_passport: Optional[str]
    additional_residency: Optional[str]
    primary_reason_for_investment: Optional[str]
    long_term_goal: Optional[str]
    interested_region_to_invest: Optional[str]
    investment_amount: Optional[str]
    liquid_cash_amount: Optional[str]
    financing_plan: Optional[str]
    require_financing_options: Optional[str]
    type_of_investment_preferred: Optional[str]
    passive_or_active_investment: Optional[str]
    current_business_status:Optional[str]
    years_of_operation: Optional[str]
    annual_revenue: Optional[str]
    monthly_income: Optional[str]
    solo_or_family: Optional[str]
    number_of_dependents: Optional[str]
    primary_tax_objective: Optional[str]
    urgency_for_residence:Optional[str]
    relocate_to_investment_country: Optional[str]
    visa_denied_previously: Optional[str]
    criminal_record: Optional[str]
    
    
    
class supervisor_state(AgentState):
    main_goal: str
    nationality: Optional[str]
    additional_passport: Optional[str]
    additional_residency: Optional[str]
    current_work_situation: Optional[str]
    current_job_industry: Optional[str]
    company_registered_at_home: Optional[str]
    will_open_company_at_abroad: Optional[str]
    monthly_income: Optional[str]
    personal_savings: Optional[str]
    destination_country: Optional[str]
    duration_of_stay: Optional[str]
    tax_benefits_option: Optional[str]
    help_open_bank_account: Optional[str]
    extend_stay_option: Optional[str]
    solo_or_family: Optional[str]
    number_of_dependents: Optional[str]
    accomodation_help: Optional[str]
    flight_booking_help: Optional[str]
    visa_denied_previously: Optional[str]
    criminal_record: Optional[str]
    primary_reason_for_investment: Optional[str]
    long_term_goal: Optional[str]
    interested_region_to_invest: Optional[str]
    investment_amount: Optional[str]
    liquid_cash_amount: Optional[str]
    financing_plan: Optional[str]
    require_financing_options: Optional[str]
    type_of_investment_preferred: Optional[str]
    passive_or_active_investment: Optional[str]
    current_business_status:Optional[str]
    years_of_operation: Optional[str]
    annual_revenue: Optional[str]
    monthly_income: Optional[str]
    solo_or_family: Optional[str]
    number_of_dependents: Optional[str]
    primary_tax_objective: Optional[str]
    urgency_for_residence:Optional[str]
    relocate_to_investment_country: Optional[str]
